import sys
import os
import time
from io import BytesIO
from html import escape
import re

import streamlit as st
from openai import OpenAI
from dotenv import load_dotenv

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)


def clean_ui_text(text):
    """Safely strips code block wrappers, converts raw HTML break tags to clean spacing, and sanitizes text for UI display."""
    if not isinstance(text, str):
        return str(text) if text is not None else ""
    cleaned = re.sub(r'```[a-zA-Z]*', '', text)
    cleaned = cleaned.replace('```', '')
    
    # Clean up raw HTML <br>, <br/>, or variant tags generated by the LLM
    cleaned = re.sub(r'<br\s*/?>', '\n', cleaned, flags=re.IGNORECASE)
    
    return cleaned.strip()


# =========================================================
# PATH SETUP
# =========================================================

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))

if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)

load_dotenv()


# =========================================================
# PROJECT IMPORT
# KEEP CURRENT WORKING BACKEND
# =========================================================

from src.orchestrator import run_lexverify_pipeline


# =========================================================
# PAGE CONFIGURATION
# =========================================================

st.set_page_config(
    page_title="LexVerify AI",
    page_icon="⚖️",
    layout="wide",
    initial_sidebar_state="expanded",
)


# =========================================================
# LEXVERIFY AI — LOVABLE-INSPIRED DESIGN SYSTEM
# =========================================================

st.markdown(
"""
<style>

/* =====================================================
   GOOGLE FONTS
   ===================================================== */

@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@500;600;700&display=swap');


/* =====================================================
   DESIGN TOKENS
   ===================================================== */

:root {
    --lv-navy: #111827;
    --lv-navy-2: #172033;
    --lv-navy-3: #202B3F;

    --lv-gold: #C5A46D;
    --lv-gold-dark: #A98750;
    --lv-gold-soft: #F4ECDF;

    --lv-cream: #F8F7F4;
    --lv-white: #FFFFFF;

    --lv-text: #172033;
    --lv-text-soft: #596273;
    --lv-text-muted: #7A8391;

    --lv-border: #E5E1D9;
    --lv-border-dark: #D8D2C7;

    --lv-green: #2F7D5A;
    --lv-green-soft: #ECF7F1;

    --lv-red: #B64B4B;
    --lv-red-soft: #FBEFEF;

    --lv-blue: #4C6FFF;
    --lv-blue-soft: #EEF2FF;

    --lv-shadow:
        0 8px 30px rgba(17, 24, 39, 0.055);

    --lv-shadow-hover:
        0 14px 35px rgba(17, 24, 39, 0.09);
}


/* =====================================================
   GLOBAL
   ===================================================== */

html,
body,
[class*="css"] {
    font-family:
        'DM Sans',
        'Inter',
        Arial,
        sans-serif;
}

.stApp {
    background: var(--lv-cream);
    color: var(--lv-text);
}

.main {
    background: var(--lv-cream);
}

.block-container {
    max-width: 1280px;
    padding-top: 1.25rem;
    padding-bottom: 2.5rem;
}


/* =====================================================
   REMOVE STREAMLIT DEFAULT TOP SPACE
   ===================================================== */

[data-testid="stAppViewContainer"] > .main {
    background: var(--lv-cream);
}

[data-testid="stHeader"] {
    background: transparent;
}


/* =====================================================
   TYPOGRAPHY
   ===================================================== */

h1,
h2,
h3,
h4 {
    font-family:
        'Playfair Display',
        Georgia,
        serif !important;

    color: var(--lv-navy) !important;
}

h1 {
    font-size: 2.45rem !important;
    font-weight: 600 !important;
    letter-spacing: -0.025em !important;
}

h2 {
    font-size: 1.75rem !important;
    font-weight: 600 !important;
}

h3 {
    font-size: 1.35rem !important;
    font-weight: 600 !important;
}

p,
li,
label,
span {
    font-family:
        'DM Sans',
        'Inter',
        Arial,
        sans-serif;
}

.stMarkdown {
    color: var(--lv-text);
}


/* =====================================================
   HERO
   ===================================================== */

.lv-hero {
    position: relative;

    overflow: hidden;

    background:
        radial-gradient(
            circle at 90% 15%,
            rgba(197,164,109,0.16),
            transparent 30%
        ),
        linear-gradient(
            135deg,
            #111827 0%,
            #172033 58%,
            #202B3F 100%
        );

    border: 1px solid rgba(197,164,109,0.25);

    border-radius: 18px;

    padding: 48px 52px;

    margin: 8px 0 28px 0;

    box-shadow:
        0 18px 45px rgba(17,24,39,0.12);
}

.lv-hero::before {
    content: "";

    position: absolute;

    width: 220px;
    height: 220px;

    right: -75px;
    top: -85px;

    border-radius: 50%;

    border: 1px solid rgba(197,164,109,0.20);
}

.lv-hero::after {
    content: "";

    position: absolute;

    width: 130px;
    height: 130px;

    right: 35px;
    bottom: -80px;

    border-radius: 50%;

    border: 1px solid rgba(197,164,109,0.13);
}

.lv-hero-kicker {
    position: relative;

    color: #D5B985;

    font-size: 11px;

    font-weight: 700;

    letter-spacing: 3px;

    text-transform: uppercase;

    margin-bottom: 13px;
}

.lv-hero-title {
    position: relative;

    font-family:
        'Playfair Display',
        Georgia,
        serif;

    color: #FFFFFF;

    font-size: clamp(40px, 5vw, 62px);

    line-height: 1.05;

    font-weight: 600;

    letter-spacing: -1.5px;

    margin-bottom: 16px;
}

.lv-hero-title span {
    color: #D5B985;
}

.lv-hero-description {
    position: relative;

    max-width: 760px;

    color: #C9D0DA;

    font-size: 15px;

    line-height: 1.75;
}

.lv-hero-rule {
    position: relative;

    width: 70px;
    height: 2px;

    margin-top: 24px;

    background:
        linear-gradient(
            90deg,
            #C5A46D,
            rgba(197,164,109,0.25)
        );
}


/* =====================================================
   SECTION HEADINGS
   ===================================================== */

.section-title {
    font-family:
        'Playfair Display',
        Georgia,
        serif;

    color: var(--lv-navy);

    font-size: 25px;

    line-height: 1.3;

    font-weight: 600;

    margin-top: 12px;
    margin-bottom: 4px;
}

.section-description {
    color: var(--lv-text-soft);

    font-size: 13px;

    line-height: 1.65;

    margin-bottom: 15px;
}


/* =====================================================
   NATIVE STREAMLIT METRIC CARDS
   ===================================================== */

[data-testid="stMetric"] {
    position: relative;

    background: var(--lv-white);

    border: 1px solid var(--lv-border);

    border-radius: 14px;

    padding: 18px 19px 17px 19px;

    min-height: 105px;

    box-shadow: var(--lv-shadow);

    transition:
        transform 0.18s ease,
        box-shadow 0.18s ease,
        border-color 0.18s ease;
}

[data-testid="stMetric"]:hover {
    transform: translateY(-2px);

    border-color: rgba(197,164,109,0.55);

    box-shadow: var(--lv-shadow-hover);
}

[data-testid="stMetric"]::before {
    content: "";

    position: absolute;

    left: 0;
    top: 14px;
    bottom: 14px;

    width: 3px;

    border-radius: 0 3px 3px 0;

    background: var(--lv-gold);
}

[data-testid="stMetricLabel"] {
    color: var(--lv-text-soft) !important;

    font-size: 12px !important;

    font-weight: 600 !important;

    letter-spacing: 0.1px;
}

[data-testid="stMetricValue"] {
    color: var(--lv-navy) !important;

    font-family:
        'Playfair Display',
        Georgia,
        serif !important;

    font-size: 29px !important;

    font-weight: 600 !important;
}

[data-testid="stMetricDelta"] {
    font-size: 11px !important;

    font-weight: 600 !important;
}


/* =====================================================
   CUSTOM METRIC CARDS
   ===================================================== */

.metric-card {
    background: var(--lv-white);

    border: 1px solid var(--lv-border);

    border-radius: 14px;

    min-height: 102px;

    padding: 17px 16px;

    text-align: center;

    box-shadow: var(--lv-shadow);

    transition:
        transform 0.18s ease,
        box-shadow 0.18s ease,
        border-color 0.18s ease;
}

.metric-card:hover {
    transform: translateY(-2px);

    border-color: rgba(197,164,109,0.55);

    box-shadow: var(--lv-shadow-hover);
}

.metric-value {
    color: var(--lv-navy);

    font-family:
        'Playfair Display',
        Georgia,
        serif;

    font-size: 26px;

    font-weight: 600;

    line-height: 1.2;
}

.metric-label {
    color: var(--lv-text-muted);

    font-size: 10px;

    font-weight: 700;

    letter-spacing: 0.7px;

    text-transform: uppercase;

    margin-top: 7px;
}


/* =====================================================
   BUTTONS
   ===================================================== */

.stButton > button,
.stFormSubmitButton > button,
[data-testid="stDownloadButton"] > button {
    min-height: 42px;

    border-radius: 9px !important;

    border: 1px solid var(--lv-border-dark) !important;

    background: var(--lv-white) !important;

    color: var(--lv-navy) !important;

    font-family:
        'DM Sans',
        'Inter',
        sans-serif !important;

    font-size: 13px !important;

    font-weight: 600 !important;

    transition:
        background 0.18s ease,
        border-color 0.18s ease,
        color 0.18s ease,
        transform 0.18s ease,
        box-shadow 0.18s ease;
}

.stButton > button:hover,
[data-testid="stDownloadButton"] > button:hover {
    background: var(--lv-gold-soft) !important;

    border-color: var(--lv-gold) !important;

    color: var(--lv-navy) !important;

    transform: translateY(-1px);

    box-shadow:
        0 6px 16px rgba(17,24,39,0.07);
}


/* PRIMARY BUTTON */

button[kind="primary"],
.stFormSubmitButton > button[kind="primary"],
[data-testid="stDownloadButton"] button[kind="primary"] {
    background:
        linear-gradient(
            135deg,
            #B58F57 0%,
            #C5A46D 50%,
            #D0B47F 100%
        ) !important;

    border: 1px solid #A98750 !important;

    color: #FFFFFF !important;

    box-shadow:
        0 7px 18px rgba(169,135,80,0.22);
}

button[kind="primary"]:hover,
.stFormSubmitButton > button[kind="primary"]:hover,
[data-testid="stDownloadButton"] button[kind="primary"]:hover {
    background:
        linear-gradient(
            135deg,
            #A98750 0%,
            #B89760 50%,
            #C5A46D 100%
        ) !important;

    color: #FFFFFF !important;

    border-color: #9C7946 !important;

    transform: translateY(-1px);

    box-shadow:
        0 9px 22px rgba(169,135,80,0.28);
}


/* =====================================================
   QUERY INPUT
   ===================================================== */

[data-testid="stTextInput"] {
    margin-top: 4px;
}

[data-testid="stTextInput"] input {
    min-height: 48px;

    background: var(--lv-white) !important;

    color: var(--lv-navy) !important;

    border: 1px solid var(--lv-border-dark) !important;

    border-radius: 10px !important;

    font-family:
        'DM Sans',
        'Inter',
        sans-serif !important;

    font-size: 13px !important;

    box-shadow:
        0 3px 12px rgba(17,24,39,0.025);
}

[data-testid="stTextInput"] input::placeholder {
    color: #969DA8 !important;
}

[data-testid="stTextInput"] input:focus {
    border-color: var(--lv-gold) !important;

    box-shadow:
        0 0 0 1px var(--lv-gold),
        0 4px 14px rgba(17,24,39,0.05) !important;
}


/* =====================================================
   TABS
   ===================================================== */

[data-testid="stTabs"] {
    margin-top: 6px;
}

[data-testid="stTabs"] [role="tablist"] {
    gap: 4px;

    border-bottom: 1px solid var(--lv-border);
}

[data-testid="stTabs"] [role="tab"] {
    color: var(--lv-text-muted);

    font-family:
        'DM Sans',
        'Inter',
        sans-serif;

    font-size: 12px;

    font-weight: 600;

    padding: 12px 15px;

    border-radius: 7px 7px 0 0;
}

[data-testid="stTabs"] [role="tab"]:hover {
    color: var(--lv-navy);

    background: rgba(197,164,109,0.07);
}

[data-testid="stTabs"] [role="tab"][aria-selected="true"] {
    color: var(--lv-navy);

    background: transparent;
}

[data-testid="stTabs"] [data-baseweb="tab-highlight"] {
    background: var(--lv-gold) !important;

    height: 2px !important;
}


/* =====================================================
   CONTAINERS / CARDS
   ===================================================== */

[data-testid="stVerticalBlockBorderWrapper"] {
    background: var(--lv-white) !important;

    border:
        1px solid var(--lv-border) !important;

    border-radius: 13px !important;

    box-shadow:
        0 5px 18px rgba(17,24,39,0.045);
}


/* =====================================================
   EXPANDERS
   ===================================================== */

[data-testid="stExpander"] {
    background: var(--lv-white);

    border:
        1px solid var(--lv-border) !important;

    border-radius: 10px !important;

    box-shadow:
        0 4px 14px rgba(17,24,39,0.035);

    overflow: hidden;
}

[data-testid="stExpander"] summary {
    color: var(--lv-navy) !important;

    font-weight: 600 !important;

    font-size: 13px !important;
}

[data-testid="stExpander"] summary:hover {
    background: var(--lv-gold-soft);
}


/* =====================================================
   CODE / SOURCE TRACE
   ===================================================== */

[data-testid="stCodeBlock"] {
    border-radius: 9px !important;

    border:
        1px solid #E1DDD5 !important;
}


/* =====================================================
   ALERTS
   ===================================================== */

[data-testid="stAlert"] {
    border-radius: 10px !important;

    font-size: 13px;
}


/* =====================================================
   INFO BOX
   ===================================================== */

[data-testid="stAlert"][kind="info"] {
    background: var(--lv-blue-soft);
}


/* =====================================================
   DIVIDERS
   ===================================================== */

hr {
    border-color: var(--lv-border) !important;

    margin-top: 24px !important;

    margin-bottom: 24px !important;
}


/* =====================================================
   SIDEBAR
   ===================================================== */

[data-testid="stSidebar"] {
    background:
        linear-gradient(
            180deg,
            #111827 0%,
            #151D2C 100%
        ) !important;

    border-right:
        1px solid rgba(197,164,109,0.18);
}

[data-testid="stSidebar"] > div:first-child {
    padding-top: 1.25rem;
}

[data-testid="stSidebar"] h1,
[data-testid="stSidebar"] h2,
[data-testid="stSidebar"] h3 {
    font-family:
        'Playfair Display',
        Georgia,
        serif !important;

    color: #FFFFFF !important;
}

[data-testid="stSidebar"] p,
[data-testid="stSidebar"] li,
[data-testid="stSidebar"] label {
    color: #C8CED8 !important;

    font-size: 12px;
}

[data-testid="stSidebar"] strong {
    color: #E0C899 !important;
}

[data-testid="stSidebar"] hr {
    border-color:
        rgba(255,255,255,0.10) !important;
}

[data-testid="stSidebar"] .stButton > button {
    background:
        rgba(255,255,255,0.055) !important;

    color: #E3E7ED !important;

    border:
        1px solid rgba(255,255,255,0.10) !important;

    border-radius: 8px !important;

    box-shadow: none !important;
}

[data-testid="stSidebar"] .stButton > button:hover {
    background:
        rgba(197,164,109,0.14) !important;

    color: #F3D7A4 !important;

    border-color:
        rgba(197,164,109,0.45) !important;
}

[data-testid="stSidebar"] [data-testid="stCaptionContainer"] {
    color: #8D97A7 !important;
}


/* =====================================================
   SPINNER
   ===================================================== */

[data-testid="stSpinner"] {
    color: var(--lv-gold) !important;
}


/* =====================================================
   FOOTER
   ===================================================== */

.footer-text {
    text-align: center;

    color: #7F8793;

    font-size: 11px;

    line-height: 1.6;

    padding:
        4px 10px 10px 10px;
}


/* =====================================================
   RESPONSIVE
   ===================================================== */

@media (max-width: 900px) {

    .block-container {
        padding-left: 1rem;
        padding-right: 1rem;
    }

    .lv-hero {
        padding: 36px 30px;
    }

    .lv-hero-title {
        font-size: 43px;
    }
}

@media (max-width: 600px) {

    .lv-hero {
        padding: 30px 23px;
    }

    .lv-hero-title {
        font-size: 37px;
    }

    .lv-hero-description {
        font-size: 13px;
    }

    [data-testid="stMetric"] {
        min-height: 95px;
    }
}

</style>
""",
unsafe_allow_html=True,
)


# =========================================================
# UI FUNCTIONS
# =========================================================

def render_engine_metrics():
    """Top-level LexVerify engine metrics."""

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.markdown(
            '<div class="metric-card"><div class="metric-value">4</div><div class="metric-label">AI Agents</div></div>',
            unsafe_allow_html=True,
        )

    with col2:
        st.markdown(
            '<div class="metric-card"><div class="metric-value">FAISS</div><div class="metric-label">Vector Retrieval</div></div>',
            unsafe_allow_html=True,
        )

    with col3:
        st.markdown(
            '<div class="metric-card"><div class="metric-value">Truth</div><div class="metric-label">Citation Registry</div></div>',
            unsafe_allow_html=True,
        )

    with col4:
        st.markdown(
            '<div class="metric-card"><div class="metric-value">PDF</div><div class="metric-label">Verified Reports</div></div>',
            unsafe_allow_html=True,
        )


def render_header():
    """Render the LexVerify legal intelligence hero."""

    # IMPORTANT:
    # The HTML below intentionally has no indentation.
    # This prevents Streamlit Markdown from interpreting
    # the HTML as a code block.

    st.markdown(
"""<div class="lv-hero"><div class="lv-hero-kicker">CITATION-GROUNDED LEGAL INTELLIGENCE</div><div class="lv-hero-title">⚖️ LexVerify <span>AI</span></div><div class="lv-hero-description">Eliminating AI hallucinations in Pakistani jurisprudence. Research, retrieve, verify, and respond using evidence-grounded legal intelligence.</div><div class="lv-hero-rule"></div></div>""",
        unsafe_allow_html=True,
    )


def render_execution_time(execution_time):
    """Display pipeline execution time."""

    if execution_time is None:
        return

    st.caption(
        f"⏱️ Pipeline execution time: "
        f"{execution_time:.2f} seconds"
    )


def render_agent_status(status):
    """Render the four-agent workflow."""

    st.markdown(
        "### 🤖 Agent Workflow"
    )

    st.caption(
        "Track the Research → Retrieval → Verification → Synthesis pipeline."
    )

    agents = [
        ("Research Agent", "research"),
        ("Retrieval Agent", "retrieval"),
        ("Verification Agent", "verification"),
        ("Synthesis Agent", "synthesis"),
    ]

    columns = st.columns(4)

    for column, (name, key) in zip(columns, agents):

        current_status = status.get(
            key,
            "pending",
        )

        if current_status == "completed":
            icon="✅"
            label = "Completed"
        elif current_status == "failed":
            icon = "❌"
            label = "Failed"
        else:
            icon = "•"
            label = "Pending"

        with column:

            with st.container(border=True):

                st.markdown(
                    f"**{icon} {name}**"
                )

                if current_status == "completed":
                    st.success(
                        label,
                        icon="✅",
                    )

                elif current_status == "failed":
                    st.error(
                        label,
                        icon="❌",
                    )

                else:
                    st.info(
                        label,
                        icon="•",
                    )


def render_response_panel(state):
    """Render the final answer inside a clean native container supporting markdown."""

    st.markdown(
        "### 🧠 Research Response"
    )

    final_answer = state.get(
        "final_answer",
        "",
    )

    if final_answer and final_answer.strip():

        cleaned_answer = clean_ui_text(str(final_answer))

        with st.container(border=True):

            st.markdown(
                "#### Legal Research Brief"
            )

            st.markdown(
                cleaned_answer
            )

    else:

        st.info(
            "No final answer was generated."
        )


def render_footer():
    """Render application footer."""

    st.divider()

    st.markdown(
        """
        <div class="footer-text">
            LexVerify AI — Citation-grounded Pakistani legal research.
            For research assistance only; not legal advice.
        </div>
        """,
        unsafe_allow_html=True,
    )


# =========================================================
# SESSION STATE
# =========================================================

if "user_query" not in st.session_state:
    st.session_state.user_query = ""

if "pipeline_state" not in st.session_state:
    st.session_state.pipeline_state = None

if "execution_time" not in st.session_state:
    st.session_state.execution_time = None

if "submitted_query" not in st.session_state:
    st.session_state.submitted_query = ""


# =========================================================
# GROQ CLIENT
# =========================================================

def create_groq_client():

    api_key = os.getenv(
        "GROQ_API_KEY"
    )

    if not api_key:
        return None

    return OpenAI(
        base_url="https://api.groq.com/openai/v1",
        api_key=api_key,
    )


# =========================================================
# PDF GENERATION
# =========================================================

def create_pdf_report(query, state, execution_time=None):
    """Generate the verified LexVerify AI PDF report."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40
    )
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("LexVerifyTitle", parent=styles["Title"], alignment=TA_CENTER, fontSize=22, leading=26, spaceAfter=15)
    heading_style = ParagraphStyle("LexVerifyHeading", parent=styles["Heading2"], fontSize=14, leading=18, spaceBefore=12, spaceAfter=8)
    body_style = ParagraphStyle("LexVerifyBody", parent=styles["BodyText"], fontSize=9.5, leading=14, spaceAfter=8)
    small_style = ParagraphStyle("LexVerifySmall", parent=styles["BodyText"], fontSize=8, leading=11, textColor=colors.grey)

    story = []
    story.append(Paragraph("LexVerify AI", title_style))
    story.append(Paragraph("Research. Retrieve. Verify. Respond.", small_style))
    story.append(Spacer(1, 15))

    story.append(Paragraph("Legal Query", heading_style))
    story.append(Paragraph(escape(str(query)), body_style))

    if execution_time is not None:
        story.append(Paragraph(f"Execution Time: {execution_time:.2f} seconds", small_style))
    
    story.append(Spacer(1, 10))

    story.append(Paragraph("Final Answer", heading_style))
    final_answer = state.get("final_answer", "")
    if not final_answer:
        final_answer = "No final answer was generated because the verification pipeline did not produce sufficient verified evidence."
    
    # Clean text and replace unicode dashes that cause black boxes (■)
    cleaned_final_answer = clean_ui_text(str(final_answer))
    cleaned_final_answer = cleaned_final_answer.replace('–', '-').replace('—', '-').replace('•', '-')

    # Convert markdown table lines into clean readable list items
    lines = cleaned_final_answer.split('\n')
    formatted_lines = []
    for line in lines:
        if line.strip().startswith('|') and '|' in line[1:]:
            if '---' in line:
                continue
            cells = [c.strip() for c in line.split('|') if c.strip()]
            if cells:
                formatted_lines.append("• " + " — ".join(cells))
        else:
            formatted_lines.append(line)
    
    cleaned_final_answer = "\n".join(formatted_lines)
    
    safe_answer = escape(cleaned_final_answer)
    safe_answer = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', safe_answer)
    safe_answer = re.sub(r'\*([^\*]+)\*', r'<i>\1</i>', safe_answer)
    safe_answer = safe_answer.replace("\n", "<br/>")
    
    story.append(Paragraph(safe_answer, body_style))

    story.append(Paragraph("Verified Citations", heading_style))
    verified_citations = state.get("verified_citations", [])
    if verified_citations:
        table_data = [[Paragraph("<b>Citation</b>", body_style), Paragraph("<b>Case</b>", body_style), Paragraph("<b>Court</b>", body_style), Paragraph("<b>Year</b>", body_style)]]
        for item in verified_citations:
            if not isinstance(item, dict): continue
            
            citation = clean_ui_text(item.get("citation", "")) or "N/A"
            citation = citation.replace('–', '-').replace('—', '-')
            case_name = clean_ui_text(item.get("case_name", item.get("title", ""))) or "N/A"
            case_name = case_name.replace('–', '-').replace('—', '-')
            court = clean_ui_text(item.get("court", "")) or "N/A"
            year = clean_ui_text(item.get("year", "")) or "N/A"
            
            table_data.append([
                Paragraph(escape(str(citation)), body_style), 
                Paragraph(escape(str(case_name)), body_style), 
                Paragraph(escape(str(court)), body_style), 
                Paragraph(escape(str(year)), body_style)
            ])

        if len(table_data) > 1:
            table = Table(table_data, colWidths=[95, 190, 100, 45], repeatRows=1)
            table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey), ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("VALIGN", (0, 0), (-1, -1), "TOP"), ("LEFTPADDING", (0, 0), (-1, -1), 5), ("RIGHTPADDING", (0, 0), (-1, -1), 5),
                ("TOPPADDING", (0, 0), (-1, -1), 5), ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]))
            story.append(table)
        else:
            story.append(Paragraph("No verified citations were available.", body_style))
    else:
        story.append(Paragraph("No verified citations were found.", body_style))

    story.append(Paragraph("Rejected / Unverified Citations", heading_style))
    rejected_citations = state.get("rejected_citations", [])
    if rejected_citations:
        for item in rejected_citations:
            if isinstance(item, dict):
                citation_text = item.get("citation", item.get("text", str(item)))
            else:
                citation_text = str(item)
            cleaned_citation_text = clean_ui_text(str(citation_text)).replace('–', '-').replace('—', '-')
            story.append(Paragraph("REJECTED — " + escape(cleaned_citation_text), body_style))
    else:
        story.append(Paragraph("No rejected citations.", body_style))

    story.append(Paragraph("Retrieved Evidence", heading_style))
    evidence_chunks = state.get("retrieved_chunks", [])
    if evidence_chunks:
        for index, chunk in enumerate(evidence_chunks, start=1):
            if not isinstance(chunk, dict): continue
            source_file = chunk.get("source_file", chunk.get("source", "Unknown source"))
            text = chunk.get("text", chunk.get("content", ""))
            
            safe_text = escape(clean_ui_text(str(text)).replace('–', '-').replace('—', '-'))
            safe_text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', safe_text)
            safe_text = re.sub(r'\*([^\*]+)\*', r'<i>\1</i>', safe_text)
            safe_text = safe_text.replace("\n", "<br/>")

            story.append(Paragraph(f"<b>Evidence {index}</b> — {escape(clean_ui_text(str(source_file)))}", body_style))
            story.append(Paragraph(safe_text, body_style))
    else:
        story.append(Paragraph("No retrieved evidence was available.", body_style))

    story.append(PageBreak())
    story.append(Paragraph("Disclaimer", heading_style))
    disclaimer = "LexVerify AI is a legal research assistance tool. It does not provide legal advice and should not be treated as a substitute for professional legal judgment. Citations and evidence shown in this report are limited to the application's verified corpus."
    story.append(Paragraph(disclaimer, body_style))

    doc.build(story)
    return buffer.getvalue()
     # -----------------------------------------------------
    # VERIFIED CITATIONS
    # -----------------------------------------------------

    story.append(
        Paragraph(
            "Verified Citations",
            heading_style,
        )
    )

    verified_citations = state.get(
        "verified_citations",
        [],
    )

    if verified_citations:

        table_data = [
            [
                Paragraph(
                    "<b>Citation</b>",
                    body_style,
                ),
                Paragraph(
                    "<b>Case</b>",
                    body_style,
                ),
                Paragraph(
                    "<b>Court</b>",
                    body_style,
                ),
                Paragraph(
                    "<b>Year</b>",
                    body_style,
                ),
            ]
        ]

        for item in verified_citations:

            if not isinstance(item, dict):
                continue

            citation = clean_ui_text(item.get("citation", ""))
            case_name = clean_ui_text(item.get("case_name", item.get("title", "")))
            court = clean_ui_text(item.get("court", ""))
            year = clean_ui_text(item.get("year", ""))

            table_data.append(
                [
                    Paragraph(
                        escape(str(citation)),
                        body_style,
                    ),
                    Paragraph(
                        escape(str(case_name)),
                        body_style,
                    ),
                    Paragraph(
                        escape(str(court)),
                        body_style,
                    ),
                    Paragraph(
                        escape(str(year)),
                        body_style,
                    ),
                ]
            )

        if len(table_data) > 1:

            table = Table(
                table_data,
                colWidths=[
                    95,
                    190,
                    100,
                    45,
                ],
                repeatRows=1,
            )

            table.setStyle(
                TableStyle(
                    [
                        (
                            "BACKGROUND",
                            (0, 0),
                            (-1, 0),
                            colors.lightgrey,
                        ),
                        (
                            "GRID",
                            (0, 0),
                            (-1, -1),
                            0.5,
                            colors.grey,
                        ),
                        (
                            "VALIGN",
                            (0, 0),
                            (-1, -1),
                            "TOP",
                        ),
                        (
                            "LEFTPADDING",
                            (0, 0),
                            (-1, -1),
                            5,
                        ),
                        (
                            "RIGHTPADDING",
                            (0, 0),
                            (-1, -1),
                            5,
                        ),
                        (
                            "TOPPADDING",
                            (0, 0),
                            (-1, -1),
                            5,
                        ),
                        (
                            "BOTTOMPADDING",
                            (0, 0),
                            (-1, -1),
                            5,
                        ),
                    ]
                )
            )

            story.append(table)

        else:

            story.append(
                Paragraph(
                    "No verified citations were available.",
                    body_style,
                )
            )

    else:

        story.append(
            Paragraph(
                "No verified citations were found.",
                body_style,
            )
        )

    # -----------------------------------------------------
    # REJECTED CITATIONS
    # -----------------------------------------------------

    story.append(
        Paragraph(
            "Rejected / Unverified Citations",
            heading_style,
        )
    )

    rejected_citations = state.get(
        "rejected_citations",
        [],
    )

    if rejected_citations:

        for item in rejected_citations:

            if isinstance(item, dict):

                citation_text = item.get(
                    "citation",
                    item.get(
                        "text",
                        str(item),
                    ),
                )

            else:

                citation_text = str(item)

            cleaned_citation_text = clean_ui_text(str(citation_text))

            story.append(
                Paragraph(
                    "REJECTED — "
                    + escape(cleaned_citation_text),
                    body_style,
                )
            )

    else:

        story.append(
            Paragraph(
                "No rejected citations.",
                body_style,
            )
        )

    # -----------------------------------------------------
    # RETRIEVED EVIDENCE
    # -----------------------------------------------------

    story.append(
        Paragraph(
            "Retrieved Evidence",
            heading_style,
        )
    )

    evidence_chunks = state.get(
        "retrieved_chunks",
        [],
    )

    if evidence_chunks:

        for index, chunk in enumerate(
            evidence_chunks,
            start=1,
        ):

            if not isinstance(chunk, dict):
                continue

            source_file = chunk.get(
                "source_file",
                chunk.get(
                    "source",
                    "Unknown source",
                ),
            )

            text = chunk.get(
                "text",
                chunk.get(
                    "content",
                    "",
                ),
            )

            story.append(
                Paragraph(
                    f"<b>Evidence {index}</b> — "
                    f"{escape(clean_ui_text(str(source_file)))}",
                    body_style,
                )
            )

            story.append(
                Paragraph(
                    escape(
                        clean_ui_text(str(text))
                    ).replace(
                        "\n",
                        "<br/>",
                    ),
                    body_style,
                )
            )

    else:

        story.append(
            Paragraph(
                "No retrieved evidence was available.",
                body_style,
            )
        )

    # -----------------------------------------------------
    # DISCLAIMER
    # -----------------------------------------------------

    story.append(
        PageBreak()
    )

    story.append(
        Paragraph(
            "Disclaimer",
            heading_style,
        )
    )

    disclaimer = (
        "LexVerify AI is a legal research assistance "
        "tool. It does not provide legal advice and "
        "should not be treated as a substitute for "
        "professional legal judgment. Citations and "
        "evidence shown in this report are limited to "
        "the application's verified corpus."
    )

    story.append(
        Paragraph(
            disclaimer,
            body_style,
        )
    )

    # -----------------------------------------------------
    # BUILD
    # -----------------------------------------------------

    doc.build(story)

    return buffer.getvalue()


# =========================================================
# TOP HEADER
# =========================================================

render_engine_metrics()

render_header()


# =========================================================
# SIDEBAR
# =========================================================

with st.sidebar:

    st.markdown(
        "## ⚖️ LexVerify AI"
    )

    st.markdown(
        """
        **Citation-grounded Pakistani legal research**

        LexVerify AI retrieves relevant Pakistani
        judgment evidence, verifies citations against
        a deterministic Truth Registry, and generates
        responses only from verified evidence.
        """
    )

    st.divider()

    st.markdown(
        "### 🎯 Demo Scenarios"
    )

    bail_button = st.button(
        "⚖️ Bail Standards",
        use_container_width=True,
    )

    fake_button = st.button(
        "🔴 Fake Citation Test",
        use_container_width=True,
    )

    corpus_button = st.button(
        "🌐 Out-of-Corpus Query",
        use_container_width=True,
    )

    st.divider()

    st.markdown(
        """
        **Pipeline**

        1. 🔎 Research
        2. 📚 Retrieval
        3. 🔐 Verification
        4. 🧠 Synthesis
        """
    )

    st.divider()

    st.caption(
        "LexVerify AI • Hackathon Prototype"
    )


# =========================================================
# DEMO QUERY HANDLERS
# =========================================================

if bail_button:
    st.session_state.user_query = "What is the bail standard in non-bailable offenses?"
    st.session_state.pipeline_state = None
    st.session_state.execution_time = None
    st.rerun()

if fake_button:
    st.session_state.user_query = "Check precedent PLD 2025 SC 999"
    st.session_state.pipeline_state = None
    st.session_state.execution_time = None
    st.rerun()

if corpus_button:
    st.session_state.user_query = "What are foreign maritime tax rates?"
    st.session_state.pipeline_state = None
    st.session_state.execution_time = None
    st.rerun()


# =========================================================
# QUESTION SECTION
# =========================================================

st.markdown(
    "### 🔎 Ask a Legal Question"
)

st.caption(
    "Enter a Pakistani legal research question or try one of the demo scenarios below."
)


# =========================================================
# SAMPLE QUERY BUTTONS
# =========================================================

col1, col2, col3 = st.columns(3)

with col1:
    if st.button(
        "⚖️ Bail Standards",
        use_container_width=True,
        key="main_bail_demo",
    ):
        st.session_state.user_query = "What is the bail standard in non-bailable offenses?"
        st.session_state.pipeline_state = None
        st.session_state.execution_time = None
        st.rerun()

with col2:
    if st.button(
        "🔴 Fake Citation Test",
        use_container_width=True,
        key="main_fake_demo",
    ):
        st.session_state.user_query = "Check precedent PLD 2025 SC 999"
        st.session_state.pipeline_state = None
        st.session_state.execution_time = None
        st.rerun()

with col3:
    if st.button(
        "🌐 Out-of-Corpus Query",
        use_container_width=True,
        key="main_corpus_demo",
    ):
        st.session_state.user_query = "What are foreign maritime tax rates?"
        st.session_state.pipeline_state = None
        st.session_state.execution_time = None
        st.rerun()


# =========================================================
# QUERY FORM
# =========================================================

with st.form(
    key="legal_query_form",
    clear_on_submit=False,
):

    user_question = st.text_input(
        "Enter your legal query:",
        value=st.session_state.user_query,
        placeholder="e.g. What is the bail standard in non-bailable offenses?",
        label_visibility="collapsed",
    )

    search_clicked = st.form_submit_button(
        "🔍 Search & Verify",
        type="primary",
        use_container_width=True,
    )


# =========================================================
# PIPELINE EXECUTION
# =========================================================

if search_clicked:
    submitted_query = user_question.strip()
    st.session_state.user_query = submitted_query

    if not submitted_query:
        st.warning("Please enter a legal question first.")
    else:
        st.session_state.pipeline_state = None
        st.session_state.execution_time = None

        client = create_groq_client()

        if client is None:
            st.error(
                "GROQ_API_KEY is not configured. Please add it to Streamlit Secrets."
            )
            st.stop()

        start_time = time.perf_counter()

        try:

            with st.spinner(
                "Running Research → Retrieval → Verification → Synthesis..."
            ):

                state = run_lexverify_pipeline(
                    submitted_query,
                    client,
                )

            st.session_state.execution_time = (
                time.perf_counter() - start_time
            )

            st.session_state.pipeline_state = state

            st.session_state.submitted_query = (
                submitted_query
            )

        except Exception as exc:

            st.session_state.execution_time = (
                time.perf_counter() - start_time
            )

            st.session_state.pipeline_state = None

            st.error(
                "LexVerify pipeline encountered an error."
            )

            st.exception(exc)


# =========================================================
# DISPLAY RESULTS
# =========================================================

state = st.session_state.pipeline_state

if state is not None:

    st.divider()

    # Retrieve core data

    verified_citations = state.get(
        "verified_citations",
        [],
    )

    rejected_citations = state.get(
        "rejected_citations",
        [],
    )

    retrieved_chunks = state.get(
        "retrieved_chunks",
        [],
    )


    # =====================================================
    # STEP 2: QUICK SUMMARY DASHBOARD
    # =====================================================

    st.markdown(
        "### 📊 Verification Summary Dashboard"
    )

    st.caption(
        "A compact overview of citation verification and Truth Registry performance."
    )

    total_cites = (
        len(verified_citations)
        + len(rejected_citations)
    )

    verified_count = len(
        verified_citations
    )

    rejected_count = len(
        rejected_citations
    )

    accuracy = (
        round(
            (verified_count / total_cites) * 100,
            1,
        )
        if total_cites > 0
        else 0
    )

    col1, col2, col3, col4 = st.columns(4)

    with col1:

        st.metric(
            label="Total Citations Analyzed",
            value=total_cites,
        )

    with col2:

        st.metric(
            label="✅ Verified Citations",
            value=verified_count,
            delta="Real Precedents",
        )

    with col3:

        st.metric(
            label="❌ Rejected Hallucinations",
            value=rejected_count,
            delta="-Caught",
            delta_color="inverse",
        )

    with col4:

        st.metric(
            label="Truth Index Accuracy",
            value=f"{accuracy}%",
        )

    st.divider()


    # =====================================================
    # STEP 3: INTERACTIVE TABS
    # =====================================================

    tab1, tab2, tab3, tab4 = st.tabs(
        [
            "🧠 Research Response",
            "✅ Citation Audit",
            "📚 Evidence Explorer",
            "📊 Pipeline Metrics",
        ]
    )


    # -----------------------------------------------------
    # TAB 1: RESEARCH RESPONSE & EXPORT
    # -----------------------------------------------------

    with tab1:

        render_response_panel(
            state
        )

        st.divider()

        final_answer = state.get(
            "final_answer",
            "",
        )

        if final_answer and final_answer.strip():

            execution_time = (
                st.session_state.execution_time
            )

            try:

                pdf_bytes = create_pdf_report(
                    st.session_state.submitted_query,
                    state,
                    execution_time,
                )

                st.download_button(
                    label="📥 Download PDF Report",
                    data=pdf_bytes,
                    file_name="lexverify_ai_legal_research_report.pdf",
                    mime="application/pdf",
                    use_container_width=True,
                    type="primary",
                )

            except Exception as exc:

                st.error(
                    f"Unable to generate PDF report: {exc}"
                )

        else:

            st.info(
                "PDF export will be available when a final research response is generated."
            )


    # -----------------------------------------------------
    # TAB 2: CITATION AUDIT
    # -----------------------------------------------------

    with tab2:

        if verified_citations:

            st.markdown(
                "### ✅ Verified Citations"
            )

            for item in verified_citations:

                if not isinstance(item, dict):
                    continue

                citation = clean_ui_text(
                    item.get(
                        "citation",
                        "Unknown citation",
                    )
                )

                case_name = clean_ui_text(
                    item.get(
                        "case_name",
                        item.get(
                            "title",
                            "Unknown case",
                        ),
                    )
                )

                court = clean_ui_text(
                    item.get(
                        "court",
                        "Unknown court",
                    )
                )

                year = clean_ui_text(
                    item.get(
                        "year",
                        "Unknown year",
                    )
                )

                # Fetch new backend variables gracefully

                reason = clean_ui_text(
                    item.get(
                        "reason",
                        item.get(
                            "citation_reason",
                            "Verified via Truth Registry.",
                        ),
                    )
                )

                source_trace = clean_ui_text(
                    item.get(
                        "source_trace",
                        "Mapped to verified vector corpus.",
                    )
                )

                with st.container(
                    border=True
                ):

                    st.markdown(
                        f"### ✅ **{citation}**"
                    )

                    # --- NEW CONDITIONAL LOGIC ---

                    meta_info = []

                    if case_name and case_name != "Unknown case":
                        meta_info.append(
                            f"**Case:** {case_name}"
                        )

                    if court and court != "Unknown court":
                        meta_info.append(
                            f"**Court:** {court}"
                        )

                    if year and year != "Unknown year":
                        meta_info.append(
                            f"**Year:** {year}"
                        )

                    if meta_info:

                        st.markdown(
                            " | ".join(meta_info)
                        )

                    # -----------------------------

                    with st.expander(
                        "🔍 View Verdict Reasoning & Trace"
                    ):

                        st.write(
                            f"**Reason:** {reason}"
                        )

                        st.code(
                            f"Source Trace Mapping:\n{source_trace}"
                        )


        if rejected_citations:

            st.markdown(
                "### ❌ Rejected / Unverified Citations"
            )

            for item in rejected_citations:

                if isinstance(item, dict):

                    citation = clean_ui_text(
                        item.get(
                            "citation",
                            item.get(
                                "text",
                                str(item),
                            ),
                        )
                    )

                    reason = clean_ui_text(
                        item.get(
                            "reason",
                            item.get(
                                "citation_reason",
                                "Hallucination caught by Truth Registry.",
                            ),
                        )
                    )

                else:

                    citation = clean_ui_text(
                        str(item)
                    )

                    reason = (
                        "Hallucination caught by Truth Registry."
                    )

                with st.container(
                    border=True
                ):

                    st.error(
                        f"✗ REJECTED — {citation}"
                    )

                    with st.expander(
                        "🔍 View Rejection Reason"
                    ):

                        st.write(
                            f"**Reason:** {reason}"
                        )


        if (
            not verified_citations
            and not rejected_citations
        ):

            st.info(
                "No citations were audited during this run."
            )


    # -----------------------------------------------------
    # TAB 3: EVIDENCE EXPLORER
    # -----------------------------------------------------

    with tab3:

        st.markdown(
            "### 📚 Retrieved Evidence"
        )

        st.caption(
            "Evidence retrieved from the Pakistani legal judgment corpus and used by the verification pipeline."
        )

        if retrieved_chunks:

            for index, chunk in enumerate(
                retrieved_chunks,
                start=1,
            ):

                if not isinstance(chunk, dict):
                    continue

                source_file = chunk.get(
                    "source_file",
                    chunk.get(
                        "source",
                        "Unknown source",
                    ),
                )

                text = chunk.get(
                    "text",
                    chunk.get(
                        "content",
                        "",
                    ),
                )

                with st.expander(
                    f"📄 Evidence {index} — "
                    f"{clean_ui_text(str(source_file))}"
                ):

                    st.markdown(
                        clean_ui_text(str(text))
                    )

        else:

            st.info(
                "No evidence chunks were retrieved."
            )


    # -----------------------------------------------------
    # TAB 4: PIPELINE METRICS
    # -----------------------------------------------------

    with tab4:

        render_execution_time(
            st.session_state.execution_time
        )

        st.divider()

        status_map = {
            "research": "completed",
            "retrieval": "completed",
            "verification": "completed",
            "synthesis": "completed",
        }

        pipeline_status = state.get(
            "status",
            "",
        )

        if pipeline_status == "research_failed":

            status_map.update(
                {
                    "research": "failed",
                    "retrieval": "pending",
                    "verification": "pending",
                    "synthesis": "pending",
                }
            )

        elif pipeline_status == "retrieval_failed":

            status_map.update(
                {
                    "retrieval": "failed",
                    "verification": "pending",
                    "synthesis": "pending",
                }
            )

        elif pipeline_status == "verification_failed":

            status_map.update(
                {
                    "verification": "failed",
                    "synthesis": "pending",
                }
            )

        elif pipeline_status == "synthesis_failed":

            status_map.update(
                {
                    "synthesis": "failed",
                }
            )

        render_agent_status(
            status_map
        )


# =========================================================
# EMPTY STATE
# =========================================================

else:

    st.info(
        "Enter a Pakistani legal research question or select a demo scenario to begin."
    )

    st.markdown(
        "### 💡 How LexVerify AI Works"
    )

    st.caption(
        "LexVerify AI uses a four-stage citation-grounded legal research workflow."
    )

    col1, col2, col3, col4 = st.columns(4)

    with col1:

        with st.container(border=True):

            st.markdown(
                "### 🔎"
            )

            st.markdown(
                "**1. Research Agent**"
            )

            st.caption(
                "Extracts useful legal search terms from the user's question."
            )

    with col2:

        with st.container(border=True):

            st.markdown(
                "### 📚"
            )

            st.markdown(
                "**2. Retrieval Agent**"
            )

            st.caption(
                "Searches the Pakistani judgment corpus using FAISS."
            )

    with col3:

        with st.container(border=True):

            st.markdown(
                "### 🔐"
            )

            st.markdown(
                "**3. Verification Agent**"
            )

            st.caption(
                "Checks citation candidates against the deterministic Truth Registry."
            )

    with col4:

        with st.container(border=True):

            st.markdown(
                "### 🧠"
            )

            st.markdown(
                "**4. Synthesis Agent**"
            )

            st.caption(
                "Generates the response using verified citations and evidence."
            )


# =========================================================
# FOOTER
# =========================================================

render_footer()