import json
from pathlib import Path

import faiss
from sentence_transformers import SentenceTransformer


# ============================================================
# PATHS
# ============================================================

ROOT = Path(__file__).resolve().parents[2]

INDEX_FILE = (
    ROOT
    / "data"
    / "faiss_index"
    / "legal_cases.faiss"
)

METADATA_FILE = (
    ROOT
    / "data"
    / "faiss_index"
    / "metadata.json"
)


# ============================================================
# EMBEDDING MODEL
# ============================================================

EMBEDDING_MODEL = "all-MiniLM-L6-v2"


# ============================================================
# DEFAULT SETTINGS
# ============================================================

DEFAULT_TOP_K = 3

# Minimum cosine similarity required for a chunk
# to be considered relevant to the legal query.
SIMILARITY_THRESHOLD = 0.30


# ============================================================
# LOAD FAISS + METADATA + EMBEDDING MODEL
# ============================================================

print("Loading LexVerify retrieval system...")

index = faiss.read_index(str(INDEX_FILE))

with open(
    METADATA_FILE,
    "r",
    encoding="utf-8"
) as f:
    metadata = json.load(f)

chunks = metadata["chunks"]

try:
    embedding_model = SentenceTransformer(EMBEDDING_MODEL, local_files_only=True)
except Exception:
    embedding_model = SentenceTransformer(EMBEDDING_MODEL)
print(
    f"Loaded {index.ntotal} FAISS vectors "
    f"and {len(chunks)} chunks."
)


# ============================================================
# REQUIRED TEAM INTERFACE
# ============================================================

def retrieve_chunks(
    search_queries: list[str],
    top_k: int = 3
) -> list[dict]:
    """
    Retrieve the most relevant legal chunks.

    Required team interface:

        retrieve_chunks(
            search_queries: list[str],
            top_k: int = 3
        ) -> list[dict]

    Parameters
    ----------
    search_queries:
        List of search queries generated by the Research Agent.

    top_k:
        Maximum number of final unique chunks to return.

    Returns
    -------
    list[dict]
        Retrieved legal evidence containing:
        - chunk_id
        - case_id
        - case_name
        - citations
        - court
        - date
        - topic
        - sections
        - principles
        - source_file
        - page
        - score
        - text
    """

    if not search_queries:
        return []

    # Remove empty queries
    queries = [
        q.strip()
        for q in search_queries
        if isinstance(q, str) and q.strip()
    ]

    if not queries:
        return []

    # Do not request more than the corpus contains
    search_k = min(
        max(top_k, 3),
        index.ntotal
    )

    candidates = {}

    # --------------------------------------------------------
    # Search once for every Research Agent query
    # --------------------------------------------------------

    for query in queries:

        query_embedding = embedding_model.encode(
            [query],
            convert_to_numpy=True,
            normalize_embeddings=True
        )

        query_embedding = query_embedding.astype(
            "float32"
        )

        scores, indices = index.search(
            query_embedding,
            search_k
        )

        for score, chunk_index in zip(
            scores[0],
            indices[0]
        ):

            if chunk_index < 0:
                continue

            chunk = chunks[int(chunk_index)]

            chunk_id = chunk.get(
                "chunk_id",
                f"index_{chunk_index}"
            )

            result = {
                "chunk_id": chunk_id,
                "case_id": chunk.get("case_id"),
                "case_name": chunk.get("case_name"),
                "citations": chunk.get(
                    "citations",
                    []
                ),
                "court": chunk.get("court"),
                "date": chunk.get("date"),
                "topic": chunk.get("topic"),
                "sections": chunk.get(
                    "sections",
                    []
                ),
                "principles": chunk.get(
                    "principles",
                    []
                ),
                "source_file": chunk.get(
                    "source_file"
                ),
                "page": chunk.get("page"),
                "score": float(score),
                "text": chunk.get("text", "")
            }

            # ------------------------------------------------
            # Deduplicate chunks returned by multiple queries
            # ------------------------------------------------

            if (
                chunk_id not in candidates
                or result["score"]
                > candidates[chunk_id]["score"]
            ):
                candidates[chunk_id] = result

    # --------------------------------------------------------
    # Sort by strongest similarity
    # --------------------------------------------------------

    # --------------------------------------------------------
    # Sort by strongest similarity
    # --------------------------------------------------------

    results = sorted(
        candidates.values(),
        key=lambda x: x["score"],
        reverse=True
    )

    # --------------------------------------------------------
    # Remove weak / unrelated results
    # --------------------------------------------------------

    results = [
        result
        for result in results
        if result["score"] >= SIMILARITY_THRESHOLD
    ]

    # --------------------------------------------------------
    # Return at most top_k relevant chunks
    # --------------------------------------------------------

    return results[:top_k]


# ============================================================
# BACKWARD-COMPATIBLE SINGLE QUERY FUNCTION
# ============================================================

def retrieve(
    query: str,
    top_k: int = 3
) -> list[dict]:
    """
    Convenience wrapper for a single query.
    """

    return retrieve_chunks(
        [query],
        top_k=top_k
    )


# ============================================================
# LOCAL TEST
# ============================================================

if __name__ == "__main__":

    print()
    print("=" * 60)
    print("LexVerify Retrieval Test")
    print("=" * 60)

    question = input(
        "Enter a legal question: "
    ).strip()

    results = retrieve_chunks(
        [question],
        top_k=3
    )

    print()
    print("=" * 60)
    print(f"Retrieved {len(results)} chunks")
    print("=" * 60)

    for number, result in enumerate(
        results,
        start=1
    ):

        print()
        print(f"RESULT {number}")
        print("-" * 60)

        print(
            "Score:",
            round(result["score"], 4)
        )

        print(
            "Chunk:",
            result["chunk_id"]
        )

        print(
            "Case:",
            result["case_name"]
        )

        print(
            "Citation:",
            ", ".join(
                result["citations"]
            )
        )

        print(
            "Court:",
            result["court"]
        )

        print(
            "Page:",
            result["page"]
        )

        print(
            "Topic:",
            result["topic"]
        )

        print()
        print("Evidence:")
        print(
            result["text"][:1000]
        )